export const ENGAGEMENT_SEED = {
  client: {
    name: "Summit 360 (Internal)",
    sponsor: "Adot Diuyan",
    sponsorTitle: "COO",
    s360Lead: "Rey Dumasig",
    s360LeadTitle: "AI Director",
    startDate: "2026-04-07",
    targetClose: "2026-05-09",
    currentWeek: 4,
    totalWeeks: 4,
    code: "S360-REC-OPS-26-04",
    engagementType: "AI Pathfinder · Recruitment & Ops Build",
    overallRAG: "green",
    overallRAGNote: "All four agents live and operational",
  },

  diagnosis: {
    enabled: true,
    summary:
      "Build a fully autonomous AI recruitment and operations backbone for Summit 360 — sourcing candidates, screening and shortlisting, managing Pathfinder success post-placement, and giving leadership full pipeline visibility — before scaling it to client engagements.",
    sections: [
      {
        label: "Context",
        body: "S360 was running recruitment and ops manually: sourcing on Indeed ad hoc, screening by hand, onboarding via Canva decks, and stitching weekly reports from Slack and JazzHR. Senior bench time on ops was estimated at 14+ hrs/week.",
      },
      {
        label: "Real Problem",
        body: "Not a tooling gap — an orchestration gap. JazzHR, Indeed, Slack, Monday.com, and Google Drive all existed. Nobody was connecting them. The data was there; the automation wasn't.",
      },
      {
        label: "Opportunity",
        body: "Build four interconnected AI agents that cover the full lifecycle — top-of-funnel sourcing through post-placement Pathfinder success — and package the same architecture as a repeatable client deliverable.",
      },
    ],
  },

  thisWeek: {
    week: 4,
    dates: "Apr 28 – May 2, 2026",
    tldr:
      "All four agents are live and operational. The recruitment loop is connected end-to-end. Outstanding: first real shortlist (May 2), outreach approval backlog needs a human owner, Pathfinder data registration in Trailblazer.",
    workstreamRAG: [
      {
        name: "Atlas Sourcing",
        rag: "green",
        note: "130 candidates in pipeline, daily reports live, JazzHR synced",
      },
      {
        name: "Atlas Recruiter",
        rag: "amber",
        note: "All flows live but end-to-end shortlist not yet run with a real candidate",
      },
      {
        name: "Atlas Trailblazer",
        rag: "green",
        note: "4 Pathfinders + 4 Summit Partners live on Monday.com",
      },
      {
        name: "Atlas OM",
        rag: "green",
        note: "Full reporting live — weekly, monthly, and KPI dashboard",
      },
    ],
    shipped: [
      "Atlas OM full reporting live (weekly narrative + monthly exec report)",
      "KPI dashboard summary embedded in Monday report",
      "Trailblazer Monday.com integration (4 Pathfinders, 4 Summit Partners)",
      "Profile Builder data package (JSON + markdown)",
      "Daily #trailblazer report (9AM KL)",
      "30/60/90-day Summit Partner check-in emails — automated, live (trailblazer@s360team.com)",
      "Appraisal reply monitoring — 48h no-reply auto-tags Adot in #pathfinders-appraisal",
      "Atlas OM engagement dashboard connected to GitHub → Vercel (real-time data pipeline)",
    ],
    next: [
      "First real shortlist run end-to-end (May 2)",
      "Candidate Q&A via email flow live (May 5)",
      "Outreach approval backlog — assign owner",
      "External pilot packaging proposal (Rey + Adot, May 5)",
    ],
    risks: [
      {
        label: "Outreach approval backlog: 123 drafts pending, no Sourcing Specialist actioning",
        severity: "high",
      },
      {
        label: "No shortlisted candidates yet — end-to-end recruiter flow untested",
        severity: "medium",
      },
      {
        label: "Trailblazer active_pathfinders.json not yet loaded into agent store",
        severity: "low",
      },
    ],
    decisions: [
      {
        label: "Who owns the outreach approval backlog?",
        asker: "Rey D.",
        needBy: "2026-05-01",
      },
      {
        label: "Package this architecture as external client deliverable — which agent first?",
        asker: "Rey D. + Adot",
        needBy: "2026-05-05",
      },
    ],
    metrics: [
      {
        label: "Candidates in pipeline",
        current: 130,
        target: 50,
        unit: "candidates",
        lowerBetter: false,
      },
      {
        label: "Agents live",
        current: 4,
        target: 4,
        unit: "of 4",
        lowerBetter: false,
      },
      {
        label: "Outreach drafts pending approval",
        current: 123,
        target: 0,
        unit: "drafts",
        lowerBetter: true,
      },
      {
        label: "Active Pathfinders monitored",
        current: 4,
        target: 4,
        unit: "Pathfinders",
        lowerBetter: false,
      },
      {
        label: "Weekly reports delivered",
        current: 4,
        target: 4,
        unit: "reports",
        lowerBetter: false,
      },
      {
        label: "Pipeline stalls detected",
        current: 0,
        target: 0,
        unit: "stalls",
        lowerBetter: true,
      },
    ],
    progress: {
      milestonesDone: 5,
      milestonesTotal: 8,
      daysElapsed: 23,
      daysTotal: 32,
    },
  },

  workstreams: [
    {
      name: "Atlas Sourcing",
      owner: "Rey D.",
      rag: "green",
      mission:
        "Top-of-funnel recruitment. JazzHR polling every 4h, personalised candidate outreach drafts, Day 3/7 follow-up sequences, Slack approval flow, daily pipeline reports.",
      deliverables: [
        {
          name: "JazzHR ↔ Indeed native integration",
          date: "2026-04-10",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Candidate pipeline store (candidates.jsonl)",
          date: "2026-04-12",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Outreach draft engine (personalised, no blasts)",
          date: "2026-04-14",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Slack approval flow (#sourcing)",
          date: "2026-04-15",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Day 3 / Day 7 follow-up sequences",
          date: "2026-04-16",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Screening question email pipeline",
          date: "2026-04-21",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "4-profile rubric scoring engine (AI/Tech, Finance/Ops, Healthcare, Sales/Marketing)",
          date: "2026-04-21",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Daily pipeline report (9AM KL, auto-post)",
          date: "2026-04-22",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "JazzHR sync (enriched profiles + engagement notes)",
          date: "2026-04-22",
          owner: "Rey D.",
          status: "done",
        },
      ],
    },
    {
      name: "Atlas Recruiter",
      owner: "Adot D. / Rey D.",
      rag: "amber",
      mission:
        "Screening, scoring, shortlisting. Picks up candidates from Sourcing, runs structured 5-competency scorecard, builds shortlists, preps S360 Profile Builder packages.",
      deliverables: [
        {
          name: "JazzHR daily applicant poll",
          date: "2026-04-15",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "5-competency scorecard engine (1–5 scale, 20% each)",
          date: "2026-04-16",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Resume scoring + structured brief",
          date: "2026-04-18",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "AI screening interview (email questionnaire)",
          date: "2026-04-19",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: 'Shortlist builder with "why this candidate" brief',
          date: "2026-04-20",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Profile Builder data package (JSON + markdown)",
          date: "2026-04-22",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Daily #recruiter report (9AM KL)",
          date: "2026-04-23",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Shortlist approval flow",
          date: "2026-04-23",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Candidate Q&A via email",
          date: "2026-05-02",
          owner: "Rey D.",
          status: "in-progress",
        },
      ],
    },
    {
      name: "Atlas Trailblazer",
      owner: "Adot D.",
      rag: "green",
      mission:
        "Post-placement Pathfinder success. Onboarding sequences, weekly pulse checks, health scoring, Summit Partner routine comms, risk/upsell signal detection.",
      deliverables: [
        {
          name: "Pathfinder onboarding sequence (Day 1/3/7/14/30 emails)",
          date: "2026-04-10",
          owner: "Adot D.",
          status: "done",
        },
        {
          name: "Weekly pulse check system (3-question survey)",
          date: "2026-04-13",
          owner: "Adot D.",
          status: "done",
        },
        {
          name: "Health scoring engine (Green/Yellow/Red thresholds)",
          date: "2026-04-14",
          owner: "Adot D.",
          status: "done",
        },
        {
          name: "Summit Partner weekly update drafts",
          date: "2026-04-16",
          owner: "Adot D.",
          status: "done",
        },
        {
          name: "Risk + upsell signal detection",
          date: "2026-04-18",
          owner: "Adot D.",
          status: "done",
        },
        {
          name: "Escalation brief drafting",
          date: "2026-04-19",
          owner: "Adot D.",
          status: "done",
        },
        {
          name: "Monday.com integration (4 Pathfinders, 4 Summit Partners live)",
          date: "2026-04-24",
          owner: "Adot D.",
          status: "done",
        },
        {
          name: "Daily #trailblazer report (9AM KL)",
          date: "2026-04-25",
          owner: "Adot D.",
          status: "done",
        },
        {
          name: "30-day Summit Partner check-in email (automated, past-date guard, CC Adot)",
          date: "2026-04-29",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "60-day Summit Partner check-in email (automated, past-date guard, CC Adot)",
          date: "2026-04-29",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "90-day Summit Partner check-in email (automated, past-date guard, CC Adot)",
          date: "2026-04-29",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Appraisal reply monitor — 48h no-reply tags Adot in #pathfinders-appraisal",
          date: "2026-04-29",
          owner: "Rey D.",
          status: "done",
        },
      ],
    },
    {
      name: "Atlas OM",
      owner: "Rey D.",
      rag: "green",
      mission:
        "Pipeline orchestration and leadership visibility. Monitors all three agents, generates weekly narrative reports, routes escalations, answers SOP questions via Google Drive.",
      deliverables: [
        {
          name: "Pipeline health monitoring (every 4h, all 3 agents)",
          date: "2026-04-18",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Weekly narrative report (Monday 8AM KL, #operations)",
          date: "2026-04-20",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Escalation routing engine (structured brief → right human)",
          date: "2026-04-21",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "SOP Q&A (Google Drive folder search, cites source doc)",
          date: "2026-04-23",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Monthly executive report (first Monday of month)",
          date: "2026-04-27",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "KPI dashboard summary (weekly, embedded in Monday report)",
          date: "2026-04-27",
          owner: "Rey D.",
          status: "done",
        },
        {
          name: "Live engagement dashboard (GitHub → Vercel, Atlas OS as control plane)",
          date: "2026-04-29",
          owner: "Rey D.",
          status: "done",
        },
      ],
    },
  ],

  riskRegister: [
    {
      id: "R-01",
      risk: "Outreach approval backlog — 123 drafts pending, no Sourcing Specialist actioning",
      impact: "high",
      likelihood: "high",
      mitigation: "Assign dedicated Sourcing Specialist; Adot to action or delegate",
      owner: "Adot",
      status: "open",
    },
    {
      id: "R-02",
      risk: "No shortlisted candidates yet — pipeline filling but end-to-end recruiter flow untested with real candidate",
      impact: "medium",
      likelihood: "medium",
      mitigation: "Push first batch through by May 2",
      owner: "Rey D.",
      status: "open",
    },
    {
      id: "R-03",
      risk: "Trailblazer active_pathfinders.json empty — data not yet loaded into agent store",
      impact: "low",
      likelihood: "high",
      mitigation: "Adot to register 4 active Pathfinders in system",
      owner: "Adot",
      status: "open",
    },
  ],

  decisionLog: [
    {
      id: "D-01",
      decision: "Sourcing approval flow via Slack reaction (✅)",
      decidedBy: "Rey",
      date: "2026-04-15",
      status: "closed",
    },
    {
      id: "D-02",
      decision: "4-profile rubric (AI/Tech, Finance/Ops, Healthcare, Sales/Marketing)",
      decidedBy: "Rey + Adot",
      date: "2026-04-20",
      status: "closed",
    },
    {
      id: "D-03",
      decision: "Monday.com as Trailblazer data source (vs. local JSON)",
      decidedBy: "Adot",
      date: "2026-04-22",
      status: "closed",
    },
    {
      id: "D-04",
      decision: "Who owns outreach approval backlog?",
      decidedBy: null,
      date: "2026-05-01",
      status: "open",
    },
    {
      id: "D-05",
      decision: "Package this architecture as external client deliverable — which agent first?",
      decidedBy: null,
      date: "2026-05-05",
      status: "open",
    },
  ],

  actions: [
    {
      id: "A-01",
      action: "Assign Sourcing Specialist to clear 123-draft approval backlog",
      owner: "Adot",
      due: "2026-05-01",
      status: "open",
    },
    {
      id: "A-02",
      action: "Run first real candidate through end-to-end shortlist flow",
      owner: "Rey D.",
      due: "2026-05-02",
      status: "open",
    },
    {
      id: "A-03",
      action: "Register 4 Pathfinders in Trailblazer agent store",
      owner: "Adot",
      due: "2026-05-01",
      status: "open",
    },
    {
      id: "A-04",
      action: "Candidate Q&A email flow",
      owner: "Rey D.",
      due: "2026-05-05",
      status: "in-progress",
    },
    {
      id: "A-05",
      action: "Draft external pilot packaging proposal",
      owner: "Rey D. + Adot",
      due: "2026-05-05",
      status: "open",
    },
    {
      id: "A-06",
      action: "Candidate Q&A live",
      owner: "Rey D.",
      due: "2026-04-23",
      status: "closed",
    },
    {
      id: "A-07",
      action: "Daily reports all four agents live",
      owner: "Rey D.",
      due: "2026-04-27",
      status: "closed",
    },
  ],

  milestones: [
    {
      date: "2026-04-07",
      label: "Engagement kicked off",
      done: true,
    },
    {
      date: "2026-04-15",
      label: "Sourcing pipeline live",
      done: true,
    },
    {
      date: "2026-04-23",
      label: "Full recruitment loop (Sourcing → Recruiter) live",
      done: true,
    },
    {
      date: "2026-04-25",
      label: "Trailblazer live with Monday.com",
      done: true,
    },
    {
      date: "2026-04-28",
      label: "Atlas OM full reporting live",
      done: true,
    },
    {
      date: "2026-05-02",
      label: "First end-to-end shortlist with real candidate",
      done: false,
      current: true,
    },
    {
      date: "2026-05-05",
      label: "Candidate Q&A via email live",
      done: false,
    },
    {
      date: "2026-05-09",
      label: "Internal handoff + external pilot packaging",
      done: false,
    },
  ],

  notes: [
    {
      kind: "folder",
      label: "SOP Folder (Google Drive)",
      href: null,
    },
    {
      kind: "slack",
      label: "#sourcing",
      href: null,
    },
    {
      kind: "slack",
      label: "#recruiter",
      href: null,
    },
    {
      kind: "slack",
      label: "#trailblazer",
      href: null,
    },
    {
      kind: "slack",
      label: "#operations",
      href: null,
    },
  ],

  proposalTracking: {
    source: "AI Agents for Recruitment & Operations — S360 Proposal",
    driveFileId: "1DBMAg2s8OGEukFkAjTAkH9Q2VsiI0KER",
    headline: "Human + AI Partnership Model — AI runs the engine room. Humans own relationships, decisions, and culture.",
    headlineMetrics: [
      { label: "Always-On AI Support", value: "24/7" },
      { label: "Faster Placement", value: "35–50%" },
      { label: "Recruiter Capacity Multiplier", value: "3–5x" },
      { label: "Cost-per-Hire Reduction", value: "40%+" },
    ],
    agents: [
      {
        id: "atlas-om",
        proposalName: "Operations Manager Agent",
        builtName: "Atlas OM",
        role: "Orchestration, Analytics, Knowledge Hub & Escalation Routing",
        proposedCapabilities: [
          { capability: "Real-time pipeline monitoring across all agents (every day, all day)", status: "done" },
          { capability: "Instant SOP Q&A from Google Drive knowledge base via Slack", status: "done" },
          { capability: "Weekly + monthly narrative reports with embedded recommendations", status: "done" },
          { capability: "Escalation routing to right human with full context", status: "done" },
          { capability: "KPI tracking across all workflows", status: "done" },
          { capability: "HubSpot integration for pipeline data", status: "not-started" },
          { capability: "Live engagement dashboard (client-facing)", status: "done" },
        ],
        proposedTools: ["Slack", "HubSpot", "Google Drive", "JazzHR"],
        builtTools: ["Slack", "Google Drive", "JazzHR", "Monday.com"],
        rag: "green",
      },
      {
        id: "atlas-sourcing",
        proposalName: "Sourcing Agent",
        builtName: "Atlas Sourcing",
        role: "Job Campaign Management, Passive Candidate Outreach & JazzHR Pipeline",
        proposedCapabilities: [
          { capability: "Post and manage job campaigns on LinkedIn Recruiter + Indeed", status: "partial" },
          { capability: "Proactive passive candidate search on LinkedIn beyond inbound", status: "not-started" },
          { capability: "Personalised Day 0 first-touch outreach", status: "done" },
          { capability: "Day 3 + Day 7 automated follow-up sequences", status: "done" },
          { capability: "Enrich and populate JazzHR with structured candidate profiles", status: "done" },
          { capability: "Daily pipeline fill rate + campaign performance report", status: "done" },
          { capability: "4-profile rubric scoring engine (AI/Tech, Finance/Ops, Healthcare, Sales/Marketing)", status: "done" },
          { capability: "Slack approval flow for outreach drafts", status: "done" },
        ],
        proposedTools: ["LinkedIn Recruiter", "Indeed", "JazzHR", "Slack"],
        builtTools: ["Indeed", "JazzHR", "Slack"],
        gaps: ["LinkedIn Recruiter integration not built — Indeed + JazzHR inbound only", "Passive LinkedIn sourcing not built"],
        rag: "amber",
      },
      {
        id: "atlas-recruiter",
        proposalName: "Recruiter Agent",
        builtName: "Atlas Recruiter",
        role: "Resume Screening, AI HR Interview, Shortlisting & Summit Partner Briefing",
        proposedCapabilities: [
          { capability: "Semantic resume screening — holistic skill-to-requirement mapping", status: "done" },
          { capability: "5-competency scorecard with written reasoning summary", status: "done" },
          { capability: "AI HR screening interview via email questionnaire", status: "done" },
          { capability: "Candidate Q&A — answer questions about role and process 24/7", status: "in-progress" },
          { capability: "Shortlist builder with ranked 'why this candidate' briefs", status: "done" },
          { capability: "S360 Profile Builder data package (JSON + markdown)", status: "done" },
          { capability: "Shortlist approval flow before Summit Partner submission", status: "done" },
          { capability: "Advance/decline candidates in JazzHR automatically", status: "done" },
        ],
        proposedTools: ["JazzHR", "Claude AI", "Profile Builder", "Slack"],
        builtTools: ["JazzHR", "Claude AI", "Profile Builder", "Slack"],
        gaps: ["End-to-end shortlist not yet run with a real candidate (target May 2)"],
        rag: "amber",
      },
      {
        id: "atlas-trailblazer",
        proposalName: "Trailblazer Agent",
        builtName: "Atlas Trailblazer",
        role: "Pathfinder Onboarding, Coaching Support, Summit Partner Liaison, Retention & Revenue Growth",
        proposedCapabilities: [
          { capability: "Pathfinder onboarding sequence (Day 1/3/7/14/30 emails)", status: "done" },
          { capability: "Weekly pulse checks + health scoring (Green/Yellow/Red)", status: "done" },
          { capability: "Routine Summit Partner communications and updates", status: "done" },
          { capability: "Risk + upsell signal detection from engagement data", status: "done" },
          { capability: "Escalation brief drafting for human Trailblazer", status: "done" },
          { capability: "30/60/90-day milestone check-in emails to Summit Partners", status: "done" },
          { capability: "Appraisal reply monitoring + 48h no-reply alert to Adot", status: "done" },
          { capability: "Monday.com integration (4 Pathfinders, 4 Summit Partners live)", status: "done" },
          { capability: "Pathfinder 24/7 first-point-of-contact Q&A via chat/Slack", status: "not-started" },
          { capability: "LMS / onboarding platform integration", status: "not-started" },
          { capability: "HubSpot upsell signal detection", status: "not-started" },
        ],
        proposedTools: ["Slack", "Google Workspace", "HubSpot", "LMS/onboarding platform"],
        builtTools: ["Slack", "Google Workspace", "Monday.com", "Gmail SMTP"],
        gaps: ["Pathfinder 24/7 chat Q&A not built", "HubSpot not integrated", "LMS not integrated"],
        rag: "green",
      },
    ],
    pipeline: [
      { step: 1, label: "Intake", actor: "Summit Partner Intake Bot", status: "not-started", note: "Guided intake form → auto-creates JazzHR entry" },
      { step: 2, label: "Sourcing", actor: "Atlas Sourcing", status: "done", note: "Indeed inbound + JazzHR enrichment + Day 0/3/7 outreach" },
      { step: 3, label: "Sourcing Specialist Review", actor: "Human", status: "blocked", note: "Approval backlog — 123 drafts pending, no specialist assigned" },
      { step: 4, label: "Screening", actor: "Atlas Recruiter", status: "done", note: "Semantic scoring + 5-competency scorecard live" },
      { step: 5, label: "AI HR Interview", actor: "Atlas Recruiter", status: "done", note: "Email questionnaire + candidate Q&A in progress" },
      { step: 6, label: "Shortlist + Profile Deck", actor: "Atlas Recruiter + Human", status: "in-progress", note: "Flow built; first real candidate run target May 2" },
      { step: 7, label: "Summit Partner Selection", actor: "Human", status: "not-started", note: "Awaiting first shortlist completion" },
      { step: 8, label: "Pathfinder Onboarding", actor: "Atlas Trailblazer", status: "done", note: "Day 1/3/7/14/30 sequences live" },
      { step: 9, label: "Ongoing Support + Pulse Checks", actor: "Atlas Trailblazer", status: "done", note: "Weekly pulse, health scoring, partner updates, 30/60/90-day emails live" },
      { step: 10, label: "Human Trailblazer Coaching", actor: "Human", status: "done", note: "Escalation briefs drafted by agent; human owns coaching" },
      { step: 11, label: "OM Orchestration + Reporting", actor: "Atlas OM", status: "done", note: "Weekly narrative, monthly exec report, KPI dashboard live" },
      { step: 12, label: "COO Strategic Review", actor: "Human", status: "done", note: "Atlas OM dashboard live for executive visibility" },
    ],
    gaps: [
      { id: "G-01", area: "Sourcing", gap: "LinkedIn Recruiter integration not built — Indeed only", impact: "medium", status: "open" },
      { id: "G-02", area: "Sourcing", gap: "Passive LinkedIn candidate proactive search not built", impact: "medium", status: "open" },
      { id: "G-03", area: "All agents", gap: "HubSpot integration not built (proposed for OM + Trailblazer)", impact: "low", status: "open" },
      { id: "G-04", area: "Trailblazer", gap: "Pathfinder 24/7 chat Q&A (first point of contact) not built", impact: "low", status: "open" },
      { id: "G-05", area: "Trailblazer", gap: "LMS / onboarding platform integration not built", impact: "low", status: "open" },
      { id: "G-06", area: "Intake", gap: "Summit Partner Intake Bot (Step 1) not built — no guided intake form", impact: "low", status: "open" },
      { id: "G-07", area: "Recruiter", gap: "End-to-end shortlist not yet run with a real candidate", impact: "high", status: "in-progress" },
    ],
  },

  priorWeeks: [
    {
      week: 3,
      dates: "Apr 21 – Apr 27, 2026",
      tldr: "Sourcing pipeline at 91 candidates. Recruiter scoring live. Trailblazer health engine live.",
      rag: "green",
      shipped: [
        "Rubric scoring engine (4-profile)",
        "Profile Builder data prep",
        "Trailblazer risk/upsell signal detection",
        "Escalation brief drafting",
      ],
      next: [
        "Atlas OM reporting",
        "Monday.com Trailblazer integration",
        "Shortlist flow",
      ],
      risks: [
        "Approval backlog growing with no assigned owner",
      ],
      decisions: [
        "Monday.com as Trailblazer data source (D-03) — closed by Adot",
      ],
    },
    {
      week: 2,
      dates: "Apr 14 – Apr 20, 2026",
      tldr: "Sourcing live. First candidates in JazzHR. Recruiter build started.",
      rag: "green",
      shipped: [
        "Outreach draft engine (personalised)",
        "Slack approval flow (#sourcing)",
        "Day 3/7 follow-up sequences",
        "JazzHR sync (enriched profiles + engagement notes)",
      ],
      next: [
        "Screening rubric",
        "Recruiter agent build",
        "Trailblazer start",
      ],
      risks: [],
      decisions: [
        "4-profile rubric (D-02) — closed by Rey + Adot",
      ],
    },
    {
      week: 1,
      dates: "Apr 7 – Apr 13, 2026",
      tldr: "Foundations laid. JazzHR ↔ Indeed wired. Sourcing pipeline store live. First architecture decisions made.",
      rag: "green",
      shipped: [
        "JazzHR ↔ Indeed native integration",
        "Candidate pipeline store (candidates.jsonl)",
        "Outreach engine draft",
        "Slack bot config",
        "Pathfinder onboarding sequence (Day 1/3/7/14/30)",
        "Weekly pulse check system",
      ],
      next: [
        "Approval flow",
        "Follow-up sequences",
        "Recruiter agent start",
      ],
      risks: [],
      decisions: [
        "Sourcing approval flow via Slack reaction ✅ (D-01) — closed by Rey",
      ],
    },
  ],
};
